name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  frontend-lint:
    name: Frontend Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16' # Specify the Node.js version you are using

      - name: Install Dependencies
        run: |
          cd frontend
          npm install

      - name: Run ESLint
        run: |
          cd frontend
          npm run lint

      - name: Run Prettier Check
        run: |
          cd frontend
          npm run format -- --check

  backend-lint:
    name: Backend Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16' # Specify the Node.js version you are using

      - name: Install Dependencies
        run: |
          cd backend
          npm install

      - name: Run ESLint
        run: |
          cd backend
          npm run lint

      - name: Run Prettier Check
        run: |
          cd backend
          npm run format -- --check