name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  frontend-lint-and-test:
    name: Frontend Lint and Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install Frontend Dependencies
        run: |
          cd frontend
          npm install

      - name: Run ESLint
        run: |
          cd frontend
          npm run lint

      - name: Run Prettier Check
        run: |
          cd frontend
          npm run format -- --check

      - name: Run Frontend Tests
        run: |
          cd frontend
          npm test -- --watchAll=false

  backend-lint-and-test:
    name: Backend Lint and Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install Backend Dependencies
        run: |
          cd backend
          npm install

      - name: Set Up Environment Variables
        run: |
          echo "PORT=5000" > backend/.env
          echo "DATABASE_URL=postgres://username:password@localhost:5432/project_ethos" >> backend/.env

      - name: Run ESLint
        run: |
          cd backend
          npm run lint

      - name: Run Prettier Check
        run: |
          cd backend
          npm run format -- --check

      - name: Run Backend Tests
        run: |
          cd backend
          npm test